### ISSUE TITLE
Standalone usage, windows support

### ISSUE THREAD

**Issue by unlight** [haarcuba/pimped_subprocess#1]
Is it possible to use script without installing by pip?
I'm getting error when trying to import:
```
ImportError: No module named 'termios'
```
Is it window issue? Any workaround on this?

**Comment by haarcuba** [comment]
it seems that there is no `pty` module on Windows (and no termios either)

I never tried it on windows, sorry :)

perhaps there's an alternative?

**Comment by unlight** [comment]
Unfortunately, Python is not my primary skill, I'm not familiar with it ecosystem.
I have no idea about alternative, but I will try to google.

**Comment by haarcuba** [comment]
do you actually need the pty functionality? what do you want to use it for?
